---
title: "Delivery_Challenge"
author: "ww44ss"
date: "Oct  2014"
output: 
    html_document:
        keep_md: true
---

```{r "get_data", echo=FALSE}

##This chunk gets the data and cleans it

delivery_data<-read.csv("delivery_data.csv")

##clean data
        ##data frame it
        delivery_data<-as.data.frame(delivery_data)
        #eliminate NA zipcodes
        delivery_data<-delivery_data[!is.na(delivery_data$pickup_zipcode),]
        ##ensure purchase prices are finite
        delivery_data<-delivery_data[!is.na(delivery_data$purchase_price),]
        
        ##I comment out the row below to get the accepted answer to teh question

        #delivery_data<-delivery_data[delivery_data$purchase_price>0,]

        str(delivery_data) ##examine the data structure 

        head(delivery_data[,c(1:2,5)])  ##look at the first few rows of interesting columns


```

##Deliveries per Zipcode

```{r "deliveries per zipcode", echo=TRUE, results='asis', fig.align='center'}

##This seciton counts deliveries by zipcode and plots the result

require(xtable)
require(ggplot2)

#find frequencies

        ##Grab the zipcode data and use table to count
        deliveries <- as.data.frame(table(delivery_data$pickup_zipcode))

        #rename columns descriptively
        colnames(deliveries)<-c("pickup_zipcode", "freq")

        ##Put zipcodes as characters for later use
        deliveries$pickup_zipcode <- as.character(deliveries$pickup_zipcode)
   
        ##plot the data
        P1 <- ggplot(deliveries, aes(x=factor(pickup_zipcode), y=freq))
        P1<- P1+geom_point(size=4, colour="blue", alpha=.7)  ##point aesthetics
        P1<- P1+xlab("zipcode")+ylab("deliveries")+ggtitle("Deliveries versus Zipcode (All)")
        P1<- P1+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

##print the plot of deliveries per zipcode
        print(P1)

      
```

##Top-Delivery Zipcodes

```{r "table of top zipcodes", fig.align='center', echo="false"}

        ##create table output of top zip codes

        ##sort data by deliveries
        deliv_sorted<-deliveries[with(deliveries, order(-freq)),]       ##sort by order frequency 
        ##this next part has to do with the behavior of R
                ##First have to conver the data back from character to integer
                ##and then bind individual columns together again.
                deliv_sorted<-cbind(as.integer(deliv_sorted$pickup_zipcode), as.integer(deliv_sorted$freq))
        ##assign column names      
        colnames(deliv_sorted)<-c("pickup_zipcode", "number_deliveries")  
        ##turn into a data frame
        deliv_sorted<-as.data.frame(deliv_sorted)

        print(deliv_sorted, row.names=FALSE)


```


###Filter for High Delivery ZipCodes > 200
```{r}

##This seciton first subsets the sorted zipcodes by delivery data (deliv_sorted) 
##for instances greater than 200,
##then creates a table fo those zipcodes
##and subsets the original data based on that set
##it results the data a delivery_data2

        ##Filter the data
        deliv_sorted2<-deliv_sorted[deliv_sorted$number_deliveries>200,]

        ##Subset the data

        delivery_data2<-delivery_data[delivery_data$pickup_zipcode %in% deliv_sorted2$pickup_zipcode,]

```

##Zipcode and Price Volume Correlation  

```{r "task two", echo=FALSE}

##This chunk of code leverages the plyr package in R
##It basically pulls he data apart by zipcode and then summarizes (counts) 
##the data falling within specific ranges

require(plyr)   ##require plyr library

##Pull data apart for management table
        purchase_stats_mgt<-ddply(delivery_data2,"pickup_zipcode",
                        summarise,
                        less_than_60=length(purchase_price[purchase_price<=60.0001]),  ##select purchase price
                        btw_60_and_120=length(purchase_price[purchase_price>60.0001 & purchase_price<=120.001]),
                        above_120=length(purchase_price[purchase_price > 120.001]))


print(purchase_stats_mgt, row.names=FALSE)

```

###

###Plot of Purchase Price Data by Zipcode

```{r "mean deliveries", echo=FALSE, fig.align='center'}

library(ggplot2)      #get ggplot library

        ##create plot using violing and log scales
        P1 <- ggplot(delivery_data2, aes(x=factor(pickup_zipcode), y=purchase_price))

        P1<-P1+geom_violin(fill = "grey80", colour = "#3366FF")  ##set aesthetic colors

        P1<-P1+scale_y_log10(breaks=c(1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000),
                             labels=c(1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000))   ##add log scale and labels

        P1<-P1+coord_cartesian(ylim = c(1, 5000))       

        P1<- P1+xlab("zipcode")+ylab("purchase price")+ggtitle("Purchase Price versus Zipcode")   ##label the plot
       
        P1<-P1+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  ##fix the x-axis

print(P1)
```

This plot is really informative.

###Purchase Price Statistics by Zip Code  

```{r "zip_code_stats", echo=FALSE}
require(plyr)   #require plyr

        ##use plyr to pull data into zipcode bundled stats 

        ##some summary stats
        purchase_stats<-ddply(delivery_data2,~pickup_zipcode,
                              summarise,
                              mean_price=mean(purchase_price), ##calculate mean
                              median_price=median(purchase_price),
                              max_price=max(purchase_price))

        ##filter for complete cases
        purchase_stats<-purchase_stats[!is.na(purchase_stats$pickup_zipcode),]

        ##plot
        P2<- ggplot(purchase_stats, aes(x=factor(pickup_zipcode), y=median_price))
        P2<- P2+geom_bar(stat="identity",colour="blue", alpha=.4, width=0.6)
        P2<- P2+xlab("Zipcode")+ylab("Price")
        P2<- P2+ggtitle("Median Purchase Price versus Zipcode")
        P2<- P2+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

##print the output
P2

```

